"""init

Revision ID: d13d230e8d2b
Revises: 
Create Date: 2022-11-18 16:44:01.330871

"""
import sqlalchemy as sa
import sqlmodel  # added
from alembic import op

# revision identifiers, used by Alembic.
revision = "d13d230e8d2b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore
        sa.Column("client_phone", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_client_contact_client_name"), "client_contact", ["client_name"], unique=False)
    op.create_index(op.f("ix_client_contact_client_phone"), "client_contact", ["client_phone"], unique=False)
    op.create_table(
        "invoice_contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore
        sa.Column("mobile", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoice_contact_mobile"), "invoice_contact", ["mobile"], unique=False)
    op.create_index(op.f("ix_invoice_contact_name"), "invoice_contact", ["name"], unique=False)
    op.create_table(
        "invoice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("client_contact_id", sa.Integer(), nullable=False),
        sa.Column("invoice_contact_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_contact_id"],
            ["client_contact.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_contact_id"],
            ["invoice_contact.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "invoiceitem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),  # type: ignore
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("desc", sqlmodel.sql.sqltypes.AutoString(), nullable=True),  # type: ignore
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoiceitem_name"), "invoiceitem", ["name"], unique=False)
    op.create_table(
        "note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=False),  # type: ignore
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_note_note"), "note", ["note"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_note_note"), table_name="note")
    op.drop_table("note")
    op.drop_index(op.f("ix_invoiceitem_name"), table_name="invoiceitem")
    op.drop_table("invoiceitem")
    op.drop_table("invoice")
    op.drop_index(op.f("ix_invoice_contact_name"), table_name="invoice_contact")
    op.drop_index(op.f("ix_invoice_contact_mobile"), table_name="invoice_contact")
    op.drop_table("invoice_contact")
    op.drop_index(op.f("ix_client_contact_client_phone"), table_name="client_contact")
    op.drop_index(op.f("ix_client_contact_client_name"), table_name="client_contact")
    op.drop_table("client_contact")
    # ### end Alembic commands ###
